### PR TITLE
Publish TS definitions with the package

### PR DESCRIPTION
**Pull request by forabi**

### CODE REVIEW

**Comment by vladimiry** [comment]
Would love to see it merged. It's quite unusual to see a project written in TS shipped without declaration files.

**Comment by streamich** [comment]
@vladimiry I remember it did no work.

**Comment by forabi** [comment]
I have a fork with this PR merged and published as `@forabi/memfs` and it works fine.

**Comment by streamich** [comment]
@forabi ah, I'll give it a look.

**Comment by streamich** [comment]
Thanks looks almost good. Only thing, when I run this I get these three errors:

```
src/volume.ts(181,14): error TS4081: Exported type alias 'TFlagsCopy' has or is using private name 'COPYFILE_EXCL'.
src/volume.ts(182,14): error TS4081: Exported type alias 'TFlagsCopy' has or is using private name 'COPYFILE_FICLONE'.
src/volume.ts(183,14): error TS4081: Exported type alias 'TFlagsCopy' has or is using private name 'COPYFILE_FICLONE_FORCE'.
```

Can you pls fix those?

**Comment by streamich** [comment]
I'm closing this as TypeScript typings are now available in this package.

**Pull request closed without merging**
