### PR TITLE
[wip] Update types node

### LINKED ISSUE #695: Support building with newer @types/node module
We'd like to build memfs module in debian with newer version of @types/node module, but build fails with this error. Please update build dependency on @types/node to at least 12.20.4.

```
$ yarnpkg upgrade @types/node@12.20.4
yarn upgrade v1.22.10
warning ../../../../package.json: No license field
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning "jest > @jest/core > jest-config > babel-jest@27.0.2" has incorrect peer dependency "@babel/core@^7.8.0".
warning " > tslint-config-common@1.6.0" has incorrect peer dependency "typescript@^3.0.1".
[5/5] Rebuilding all packages...
success Saved lockfile.
success Saved 1 new dependency.
info Direct dependencies
└─ @types/node@12.20.4
info All dependencies
└─ @types/node@12.20.4
Done in 8.13s.
(debian-sid)pravi@mahishi:~/forge/js-team/upstream/memfs$ yarnpkg build
yarn run v1.22.10
warning ../../../../package.json: No license field
$ tsc -p . && cpy src/*.js lib
src/volume.ts:433:15 - error TS2769: No overload matches this call.
  Overload 1 of 5, '(arrayBuffer: ArrayBuffer | SharedArrayBuffer, byteOffset?: number | undefined, length?: number | undefined): Buffer', gave the following error.
    Argument of type 'string' is not assignable to parameter of type 'ArrayBuffer | SharedArrayBuffer'.
  Overload 2 of 5, '(obj: { valueOf(): string | object; } | { [Symbol.toPrimitive](hint: "string"): string; }, byteOffset?: number | undefined, length?: number | undefined): Buffer', gave the following error.
    Argument of type 'string' is not assignable to parameter of type 'number | undefined'.
  Overload 3 of 5, '(str: string, encoding?: BufferEncoding | undefined): Buffer', gave the following error.
    Argument of type 'string' is not assignable to parameter of type 'BufferEncoding | undefined'.

433   else return bufferFrom(String(data), encoding);
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



Found 1 error.

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

### PR DESCRIPTION
**Pull request by pravi**
A possible update, though not sure if this is correct. Fixes #695

### CODE REVIEW

**Comment by williamstein** [comment]
For what it is worth, I updated the node types for https://www.npmjs.com/package/@cowasm/memfs in this commit:

https://github.com/sagemathinc/memfs-js/commit/08b2386a4e56d88ca61f528de3133f77c04ff0d8

I don't know if a new PR is welcome for this especially since there's some choices and maybe danger.

**Comment by G-Rath** [comment]
I'm not sure if we actually want to be doing this because we target Node 4+, and what our dependency is for building shouldn't matter to downstream consumers since its not a "runtime" dependency (granted with `@types/node` that can get a bit fuzzy depending on what types we use, but we shouldn't be using a lot of actual types from there)

**Comment by G-Rath** [comment]
[See my comment on the issue](https://github.com/streamich/memfs/issues/695#issuecomment-1302524895)

**Comment by G-Rath** [comment]
Closing due to age

**Pull request closed without merging**
