### PR TITLE
feat(volume): support the recursive option for fs.watch()

### LINKED ISSUE #883: .rename/.renameSync could not trigger FSWatcher when changes are recursive
Renaming the direct child in the folder works as expect.

When I watch `/` (with `recursive: true`) and rename the `/test/hello.txt` file, the watcher is not triggered.

Here is the online demo: https://codesandbox.io/s/stoic-jerry-juxpw4?file=/src/index.js:0-264

```javascript
// demo code
import { fs } from "memfs";

fs.mkdirSync("/test");
fs.writeFileSync("/test/hello.txt", "World!");

fs.watch("/", { recursive: true }, (eventType, filename) => {
  console.log("watch:", eventType, filename);
});

fs.renameSync("/test/hello.txt", "/test/hello1.txt");
// expect print: watch: change /
```

Such code works in Node.js (v14.19.3).

### PR DESCRIPTION
**Pull request by alienzhou**
The `fs.watch` API has `recursive` option but it did not implement it. For example, the watching listener below will not be triggered:

```js
const vol = new Volume();
vol.mkdirSync('/test');

vol.watch('/', { recursive: true }, (eventType, filename) => {
  // won't be triggered
  console.log('fs.watch', eventType, filename);
});

setTimeout(() => {
  vol.writeFileSync('/test/lol.txt', '2');
}, 1000);
```

---

Besides when a child file's content (not recursive) is changed, the listener will not be triggered too:

```js
const vol = new Volume();
vol.mkdirSync('/test');
vol.writeFileSync('/test/lol.txt', 'foo')

vol.watch('/test', { recursive: false }, (eventType, filename) => {
  // won't be triggered
  console.log('fs.watch', eventType, filename);
});

setTimeout(() => {
  vol.writeFileSync('/test/lol.txt', 'bar');
}, 1000);
```

Resolves #883

### CODE REVIEW

**Review by G-Rath — APPROVED** [review]

**Comment by G-Rath** [comment]
Does this resolve #883 by chance?

**Comment by alienzhou** [comment]
> Does this resolve #883 by chance?

Yes. I added a new test case for #883  just now.

**Comment by G-Rath** [comment]
fyi this is causing the tests that were added as part of https://github.com/streamich/unionfs/pull/557 in `unionfs` to fail - I'm not sure if that is because of a bug in this code, in `unionfs`, or in the test suite

**Comment by G-Rath** [comment]
I think this implementation is buggy 

<details>
<summary>Running the test using the native file system results in the file watcher being called only once and with `foo.js` (instead of twice and with `/tmp/foo.js`)</summary>

```
import { Volume } from '../volume';

function sleep(millisec: number): Promise<void> {
  return new Promise<void>((resolve, reject) => {
    setTimeout(resolve, millisec);
  });
}

describe('volume', () => {
  it('should create a watcher', async () => {
    const ufs = require('fs');
    ufs.writeFileSync('/tmp/foo.js', 'hello test');

    const mockCallback = jest.fn();
    const writtenContent = 'hello world';
    const watcher = ufs.watch('/tmp/foo.js', mockCallback as any);

    try {
      ufs.writeFileSync('/tmp/foo.js', writtenContent);

      await sleep(3000);

      expect(mockCallback).toBeCalledTimes(2);
      expect(mockCallback).toBeCalledWith('change', '/tmp/foo.js');
    } finally {
      watcher.close();
    }
  });
});
```
</details>

<details>
<summary>Running the test with `memfs` _before_ this change results in the test passing</summary>

```
import { Volume } from '../volume';

function sleep(millisec: number): Promise<void> {
  return new Promise<void>((resolve, reject) => {
    setTimeout(resolve, millisec);
  });
}

describe('volume', () => {
  it('should create a watcher', async () => {
    const ufs = Volume.fromJSON({ '/tmp/foo.js': 'hello test' });
//    const ufs = require('fs');
    ufs.writeFileSync('/tmp/foo.js', 'hello test');

    const mockCallback = jest.fn();
    const writtenContent = 'hello world';
    const watcher = ufs.watch('/tmp/foo.js', mockCallback as any);

    try {
      ufs.writeFileSync('/tmp/foo.js', writtenContent);

      await sleep(3000);

      expect(mockCallback).toBeCalledTimes(2);
      expect(mockCallback).toBeCalledWith('change', '/tmp/foo.js');
    } finally {
      watcher.close();
    }
  });
});
```
</details>

<details>
<summary>Running the test with `memfs` _after_ this change results in the test failing as being called with an empty string twice</summary>

```
import { Volume } from '../volume';

function sleep(millisec: number): Promise<void> {
  return new Promise<void>((resolve, reject) => {
    setTimeout(resolve, millisec);
  });
}

describe('volume', () => {
  it('should create a watcher', async () => {
    const ufs = Volume.fromJSON({ '/tmp/foo.js': 'hello test' });
//    const ufs = require('fs');
    ufs.writeFileSync('/tmp/foo.js', 'hello test');

    const mockCallback = jest.fn();
    const writtenContent = 'hello world';
    const watcher = ufs.watch('/tmp/foo.js', mockCallback as any);

    try {
      ufs.writeFileSync('/tmp/foo.js', writtenContent);

      await sleep(3000);

      expect(mockCallback).toBeCalledTimes(2);
      expect(mockCallback).toBeCalledWith('change', '/tmp/foo.js');
    } finally {
      watcher.close();
    }
  });
});
```
</details>

**Pull request merged**
