### PR TITLE
add volume.fromDirectory to service data migration

### PR DESCRIPTION
**Pull request by alexsunday**
for some special situation, we need data from exists filesystem, so, add a method on Volume.

### CODE REVIEW

**Review by G-Rath — CHANGES_REQUESTED** [review]
Can you please add some tests?

**Comment by alexsunday** [comment]
> Can you please add some tests?
> 
> You also need to apply formatting

OK，added a case, and pretty the code.

**Comment by G-Rath** [comment]
It doesn't look like you're attempting to copy any of the properties on the files - I feel like we should be doing that, though also I this is why we've generally not provided a utility method like this as people might want different behaviours depending on the use-case 🤔

**Comment by alexsunday** [comment]
yes, file properties not copied, this is because there is no corresponding field for the type 'DirectoryJSON' in the code. I though that 'DirectoryJSON' was not prepared to save all the file attribute here?

I see that the example code on readme.md, section 'Usage' , the json struct is very simple, 
but sometimes when we want to express the files in exists filesystem, it will be more convenient if there is a method available.

if you  fell it's unnecessary, just close pr.

**Comment by alexsunday** [comment]
please close this pr, use json store binary file is a wrong way.

**Comment by alexsunday** [comment]
use json store binary file is a wrong way, closed.

**Comment by G-Rath** [comment]
@alexsunday I'm not sure what you mean?

**Pull request closed without merging**
