### PR TITLE
feat(volume): extended `vol.toJSON` with the `asBuffer` parameter

### PR DESCRIPTION
**Pull request by shorwood**
## Context

Review feedback from the #880.
Note that this PR is isolated and does not include #880 

## Actions

Extended `vol.toJSON` so it can now output the virtual directory structure as a map of `Buffer` if the `asBuffer` parameter is set to `true`

### CODE REVIEW

**Comment by G-Rath** [comment]
I assume you've not updated the return type because that's handled in #880?

**Comment by shorwood** [comment]
To simplify things, I rebased this branch on the branch from #880.

**Comment by shorwood** [comment]
To streamline this PR, and since `toJSON` and `fromJSON` are kind of in the same scope, I'm closing this PR and merging this feature into #800

**Comment by G-Rath** [comment]
@shorwood I'd prefer them as separate PRs because what you're doing in #880 is a bit different and I'd like the changes to have at least their own lines in the changelog. I'm happy though if you want to just do one PR at a time.

**Comment by shorwood** [comment]
Alright, reverting the changes.

**Comment by shorwood** [comment]
Done.

**Comment by shorwood** [comment]
#952

**Pull request closed without merging**
