### PR TITLE
feat(volume): add caseSensitive option

### PR DESCRIPTION
**Pull request by ajafff**
Defaults to 'true'. If 'false', handle file names case insensitive.
Preserve original file names.

Fixes: #533

### CODE REVIEW

**Comment by G-Rath** [comment]
I'll review this properly when I have a chance, but for now: I think I'd prefer this option to be `ignoreCase` with a default of `false` rather than have an option with a default of `true` as that tends to be easier to reason mentally.

**Comment by ajafff** [comment]
@G-Rath that makes sense. I'll update the PR accordingly.

I noticed that the sorting of `readdir(Sync)` should also respect case sensitivity. I'm currently working on that.

I should probably also update the docs.

**Comment by tstordyallison** [comment]
+1 for this. I'm playing around with using memfs in conjunction with some libraries that are assuming case-insensitivity on Windows platforms, which isn't the case when I'm using memfs! This would be an ideal fix.

**Comment by jburrow** [comment]
+1 Just hit the same issue with memfs on windows

**Comment by G-Rath** [comment]
Closing due to age - feel free to rebase this PR or open a new one if someone wants to pick it back up

**Pull request closed without merging**
